name: Lint

env:
  NODE_VERSION: 18

on:
  pull_request:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3
      - uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - run: npm ci
      - run: npm ls --depth=0

      - uses: ./
        with:
          extensions: 'js,ts'
          ignore-patterns: dist/
